name = input("Ваше ім'я:")
surname = input("Ваше прізвище:")
age = input("Ваш вік:")
city = input("Ваше місто:")
print("Ім'я: " + name)
print("Прізвище: " + surname)
print("Вік: " + age)
print("Місто: " + city)